/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DomainModels.KhachHang;
import Service.Service_Implement.KhachHang_Service_Impl;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class ThongTinKhachHang extends javax.swing.JFrame {
    KhachHang_Service_Impl khachHangSV = new KhachHang_Service_Impl();
    
    public ThongTinKhachHang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtHo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgaySinh = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnXacNhan = new javax.swing.JButton();
        txtTenDem = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTen = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtThanhPho = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtQuocGia = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtMa = new javax.swing.JTextField();
        sdfgdzg = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblSoDienThoai = new javax.swing.JLabel();
        lblQueQuan = new javax.swing.JLabel();
        btnDangNhap = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập Thông Tin Người Dùng");

        jLabel3.setText("Họ");

        jLabel4.setText("Ngày sinh:");

        jLabel5.setText("Số điện thoại:");

        jLabel6.setText("Địa chỉ");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel7.setText("Tên đệm");

        jLabel8.setText("Tên");

        jLabel9.setText("Thành phố");

        jLabel10.setText("Quốc gia");

        sdfgdzg.setText("Mã");

        lblMa.setForeground(new java.awt.Color(255, 0, 51));

        lblHoTen.setForeground(new java.awt.Color(255, 0, 51));

        lblNgaySinh.setForeground(new java.awt.Color(255, 0, 51));

        lblSoDienThoai.setForeground(new java.awt.Color(255, 0, 51));

        lblQueQuan.setForeground(new java.awt.Color(255, 0, 51));

        btnDangNhap.setText("Trở về");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdfgdzg, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(txtThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblMa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(txtMa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtTenDem, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(lblSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(txtQuocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(155, 155, 155)
                        .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(lblQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtHo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTenDem, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtTen, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sdfgdzg, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSoDienThoai)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtThanhPho, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuocGia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblQueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        if (check()) {
            KhachHang kh = getForm();
            if (kh == null) {
                return;
            }
            int choice = JOptionPane.showConfirmDialog(this, "Insert", "confirm", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                khachHangSV.updateKhachHang(kh);
                JOptionPane.showMessageDialog(this, "Thêm thông tin thành công");
            }

        }
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnDangNhapActionPerformed

    
    private KhachHang getForm() {
        String ma = txtMa.getText();
        String ten = txtTen.getText();
        String tenDem = txtTenDem.getText();
        String ho = txtHo.getText();
        String ngaySinh = txtNgaySinh.getText();
        String sdt = txtSoDienThoai.getText();
        String diaChi = txtDiaChi.getText();
        String thanhPho = txtThanhPho.getText();
        String quocGia = txtQuocGia.getText();

        KhachHang kh = new KhachHang(ma, ten, tenDem, ho, ngaySinh, sdt, diaChi, thanhPho, quocGia, null, null);
        return kh;
    }

    private boolean check() {
        if (txtMa.getText().equals("") && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && (txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (!(txtMa.getText().equals("")) && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && (txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (txtMa.getText().equals("") && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && txtNgaySinh.getText().equals("") && txtSoDienThoai.getText().equals("")
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (txtMa.getText().equals("") && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && !(txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (txtMa.getText().equals("") && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && (txtNgaySinh.getText().equals("")) && !(txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (txtMa.getText().equals("") && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && (txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals("")))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("");
            return false;
        }
        if (!(txtMa.getText().equals("")) && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && txtNgaySinh.getText().equals("") && txtSoDienThoai.getText().equals("")
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("");
            lblHoTen.setText("");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (!(txtMa.getText().equals("")) && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && !(txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (!(txtMa.getText().equals("")) && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && (txtNgaySinh.getText().equals("")) && !(txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if(!(txtHo.getText().equals("") || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))){
            lblHoTen.setText("");
        }
        if (!(txtMa.getText().equals("")) && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && (txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals("")))) {
            lblMa.setText("");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("");
            return false;
        }
        if ((txtMa.getText().equals("")) && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && !(txtNgaySinh.getText().equals("")) && txtSoDienThoai.getText().equals("")
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if ((txtMa.getText().equals("")) && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && (txtNgaySinh.getText().equals("")) && !(txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if ((txtMa.getText().equals("")) && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && (txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals("")))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("");
            return false;
        }
        if (txtMa.getText().equals("") && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && (txtNgaySinh.getText().equals("")) && !(txtSoDienThoai.getText().equals(""))
                && (!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals("")))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("");
            lblQueQuan.setText("");
            return false;
        }
        if (!(txtMa.getText().equals("")) && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && !(txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("");
            lblHoTen.setText("");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (!(txtMa.getText().equals("")) && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && (txtNgaySinh.getText().equals("")) && !(txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("");
            lblHoTen.setText("");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (!(txtMa.getText().equals("")) && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && (txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals("")))) {
            lblMa.setText("");
            lblHoTen.setText("");
            lblNgaySinh.setText("*Vui lòng nhập ngày sinh!");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("");
            return false;
        }
        if (txtMa.getText().equals("") && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && !(txtNgaySinh.getText().equals("")) && !(txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (txtMa.getText().equals("") && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && !(txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals("")))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("");
            return false;
        }
        if (txtMa.getText().equals("") && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && !(txtNgaySinh.getText().equals("")) && !(txtSoDienThoai.getText().equals(""))
                && (!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals("")))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("");
            lblQueQuan.setText("");
            return false;
        }
        if (!(txtMa.getText().equals("")) && (txtHo.getText().equals("") || txtTenDem.getText().equals("") || txtTen.getText().equals(""))
                && !(txtNgaySinh.getText().equals("")) && !(txtSoDienThoai.getText().equals(""))
                && (!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals("")))) {
            lblMa.setText("");
            lblHoTen.setText("*Vui lòng nhập đầy đủ họ tên!");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("");
            lblQueQuan.setText("");
            return false;
        }
        if (!(txtMa.getText().equals("")) && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && !(txtNgaySinh.getText().equals("")) && !(txtSoDienThoai.getText().equals(""))
                && (txtDiaChi.getText().equals("") || txtThanhPho.getText().equals("") || txtQuocGia.getText().equals(""))) {
            lblMa.setText("");
            lblHoTen.setText("");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("");
            lblQueQuan.setText("*Vui lòng nhập đầy đủ thông tin địa chỉ!");
            return false;
        }
        if (txtMa.getText().equals("") && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && !(txtNgaySinh.getText().equals("")) && !(txtSoDienThoai.getText().equals(""))
                && (!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals("")))) {
            lblMa.setText("*Vui lòng nhập mã!");
            lblHoTen.setText("");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("");
            lblQueQuan.setText("");
            return false;
        }
        if (!(txtMa.getText().equals("")) && (!(txtHo.getText().equals("")) || !(txtTenDem.getText().equals("")) || !(txtTen.getText().equals("")))
                && !(txtNgaySinh.getText().equals("")) && (txtSoDienThoai.getText().equals(""))
                && (!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals("")))) {
            lblMa.setText("");
            lblHoTen.setText("");
            lblNgaySinh.setText("");
            lblSoDienThoai.setText("*Vui lòng nhập số điện thoại!");
            lblQueQuan.setText("");
            return false;
        }
        if(!(txtDiaChi.getText().equals("")) || !(txtThanhPho.getText().equals("")) || !(txtQuocGia.getText().equals(""))){
            lblQueQuan.setText("");
        }
        Pattern sp = Pattern.compile("[!@#$%&*()_.,/?';:+=|<>?{}\\[\\]~-[a-z]]", Pattern.CASE_INSENSITIVE);
        Matcher mt = sp.matcher(txtSoDienThoai.getText());
        boolean cons = mt.find();
        {
            if (cons == true) {
                lblSoDienThoai.setText("Vui long nhap so dien thoai");
                txtSoDienThoai.requestFocus();
                return false;
            }
        }
        SimpleDateFormat sim = new SimpleDateFormat();
        sim.applyPattern("dd-mm-yyyy");
        Date d;
        try {
            d = sim.parse(txtNgaySinh.getText());
            lblNgaySinh.setText("");
        } catch (Exception e) {
            e.printStackTrace();
            lblNgaySinh.setText("Vui lòng nhập đúng định dạng ngày tháng");
            return false;
        }
        Pattern sp1 = Pattern.compile("[!@#$%&*()_.,/?';:+=|<>?{}\\[\\]~-]", Pattern.CASE_INSENSITIVE);
        Matcher mt1 = sp1.matcher(txtSoDienThoai.getText());
        boolean cons1 = mt1.find();
        {
            if (cons1 == true) {
                lblSoDienThoai.setText("Vui long nhap so");
                txtSoDienThoai.requestFocus();
                return false;
            }
        }
        if (txtSoDienThoai.getText().length() != 10) {
            lblSoDienThoai.setText("Vui lòng nhập số điện thoại có 10 số");
            return false;
        }
        if (txtSoDienThoai.getText().length() == 10) {
            lblSoDienThoai.setText("");
        }
        Pattern sp2 = Pattern.compile("[!@#$%&*()_.,/?';:+=|<>?{}\\[\\]~-]", Pattern.CASE_INSENSITIVE);
        Matcher mt2 = sp2.matcher(txtDiaChi.getText());
        boolean cons2 = mt2.find();
        {
            if (cons2 == true) {
                txtDiaChi.setText("Vui long nhap so");
                txtDiaChi.requestFocus();
                return false;
            }
        }

        return true;
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblQueQuan;
    private javax.swing.JLabel lblSoDienThoai;
    private javax.swing.JLabel sdfgdzg;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtHo;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtQuocGia;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTen;
    private javax.swing.JTextField txtTenDem;
    private javax.swing.JTextField txtThanhPho;
    // End of variables declaration//GEN-END:variables
}
